name: practice

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

         # - name: Build application
         #  run: npm run build

      - name: Deploy to server
        run: |
         # npm install
         # npm run build
          run express
          cd ~/practice
          git pull origin main
          npm 
           ssh -i "backend-deployment.pem" ubuntu@ec2-65-0-102-109.ap-south-1.compute.amazonaws.com"
